production: &production
  adapter: em_postgresql
  encoding: unicode
  database: skit
  pool: 5
  username: postgres
  password: 
  min_messages: WARNING
  host: localhost
development:
  <<: *production